### ISSUE TITLE
Villager type and profession texture not work on server

### ISSUE THREAD

**Issue by YoungSoulluoS** [OverlordsIII/NPCVarietyPort#21]
Hi, thanks you for good mod.
Villager type and profession texture not work on server.
At the same time Zombie Villager works as needed.

p.s. 
I saw 
**Note 2: This mod is required both on the client and the server side to work as intended.**
 But my server is Paper. And if the Zombie Villagers are working, then maybe the Villagers can be fixed.

**Comment by YoungSoulluoS** [comment]
![2022-09-28_11 39 51](https://user-images.githubusercontent.com/70120313/192706535-7ab50780-9ed8-4942-a5e2-50deebd04d8e.png)

**Comment by OverlordsIII** [comment]
Unfortunately, it's impossible to have the mod work without the serverside part implemented. This is because each villager has a variant of their eyes and skin, which the server tracks. Zombie villagers don't have this tracking needed but will if you zombify a villager. I'd recommend getting a new server with fabric on it, possibly using something like Aternos.

**Comment by YoungSoulluoS** [comment]
Ok. I'll try it then - adjust the internal texturepack to make it work through random textures, like in optifine.
